// OpenDAW Agents with Collaboration Integration
// Generated by synxSphere collaboration integration

import {FloatArray, int, Procedure} from "std"
import WorkerUrl from "../worker/agents.ts?worker&url"
import {Entry, OpfsProtocol, PeakProtocol} from "fusion"
import {Communicator, Messenger} from "runtime"

// Import collaboration components
import { CollaborationManager } from '../collaboration/CollaborationManager'

// Variable to store StudioService reference
let studioServiceRef: any = null

// Function to set the StudioService reference for collaboration
export function setStudioServiceForCollaboration(service: any) {
    studioServiceRef = service
    console.log('🔗 StudioService reference set for collaboration')
}

const messenger = Messenger.for(new Worker(WorkerUrl, {type: "module"}))

export const PeakAgent = Communicator.sender<PeakProtocol>(messenger.channel("peaks"),
    router => new class implements PeakProtocol {
        async generateAsync(
            progress: Procedure<number>,
            shifts: Uint8Array,
            frames: ReadonlyArray<FloatArray>,
            numFrames: int,
            numChannels: int): Promise<ArrayBufferLike> {
            return router.dispatchAndReturn(this.generateAsync, progress, shifts, frames, numFrames, numChannels)
        }
    })

// Create the base OPFS agent
const baseOpfsAgent = Communicator.sender<OpfsProtocol>(messenger.channel("opfs"),
    router => new class implements OpfsProtocol {
        write(path: string, data: Uint8Array): Promise<void> {return router.dispatchAndReturn(this.write, path, data)}
        read(path: string): Promise<Uint8Array> {return router.dispatchAndReturn(this.read, path)}
        delete(path: string): Promise<void> {return router.dispatchAndReturn(this.delete, path)}
        list(path: string): Promise<ReadonlyArray<Entry>> {return router.dispatchAndReturn(this.list, path)}
    })

// Create a proxy that will route to the appropriate agent
let currentOpfsAgent = baseOpfsAgent
let collaborationInitialized = false
let collaborationManager: CollaborationManager | null = null

// Check for collaboration mode
const urlParams = new URLSearchParams(window.location.search)
const projectId = urlParams.get('projectId')
const userId = urlParams.get('userId')
const userName = urlParams.get('userName') || userId
const isCollaborative = urlParams.get('collaborative') === 'true'

console.log('🔍 OpenDAW Collaboration Check:', { projectId, userId, isCollaborative })

if (isCollaborative && projectId && userId) {
    console.log('🤝 Initializing collaboration mode...')
    
    try {
        // Initialize collaboration manager
        // Use environment variables or defaults
        const wsUrl = import.meta.env.VITE_COLLABORATION_WS_URL || 'wss://localhost:8443/ws'
        const httpUrl = import.meta.env.VITE_COLLABORATION_HTTP_URL || 'http://localhost:3003'
        
        collaborationManager = new CollaborationManager({
            projectId,
            userId,
            userName: userName || userId,
            wsUrl: wsUrl,
            dbUrl: httpUrl, // Use HTTP URL for API calls
            studioService: studioServiceRef
        })
        
        // Initialize collaboration asynchronously
        collaborationManager.initialize(baseOpfsAgent).then((collaborativeAgent: any) => {
            console.log('✅ Collaboration initialized successfully')
            
            // Switch to the collaborative agent
            currentOpfsAgent = collaborativeAgent
            collaborationInitialized = true
            
            // PERFORMANCE FIX: Remove redundant audio pre-loading 
            // The CollaborationManager.initialize() already calls:
            // 1. loadExistingProject() - which loads audio files
            // 2. requestSync() - which may trigger additional audio loading
            // So we don't need this additional setTimeout trigger
            console.log('� COLLAB-INIT: Audio loading handled by CollaborationManager initialization')
            
            // Only process pending load-project message if it exists
            const pendingMessage = (window as any).pendingLoadProjectMessage
            if (pendingMessage) {
                console.log('� COLLAB-INIT: Processing pending load-project message')
                collaborativeAgent.handleCollaborationMessage(pendingMessage)
                delete (window as any).pendingLoadProjectMessage
            }
            
            // Add visual indicators
            const style = document.createElement('style')
            style.textContent = `
                .collaboration-active {
                    border-top: 2px solid #10b981 !important;
                }
                .collaboration-panel {
                    position: fixed;
                    top: 50px;
                    right: 10px;
                    background: rgba(0, 0, 0, 0.85);
                    color: white;
                    padding: 8px 10px;
                    border-radius: 6px;
                    font-family: system-ui, -apple-system, sans-serif;
                    font-size: 11px;
                    z-index: 9999;
                    border: 1px solid #10b981;
                    min-width: 140px;
                    max-width: 180px;
                    backdrop-filter: blur(4px);
                }
                .collaboration-panel h4 {
                    margin: 0 0 4px 0;
                    color: #10b981;
                    font-size: 12px;
                    font-weight: 600;
                }
                .collab-user {
                    display: flex;
                    align-items: center;
                    gap: 4px;
                    margin: 2px 0;
                    font-size: 10px;
                }
                .collab-status {
                    width: 6px;
                    height: 6px;
                    border-radius: 50%;
                    background: #10b981;
                    flex-shrink: 0;
                }
                .collab-info {
                    font-size: 10px;
                    color: #a0a0a0;
                    margin: 2px 0;
                }
            `
            document.head.appendChild(style)
            
            // Add collaboration panel to UI
            const panel = document.createElement('div')
            panel.className = 'collaboration-panel'
            panel.innerHTML = `
                <h4>🤝 Collaboration</h4>
                <div class="collab-user">
                    <div class="collab-status"></div>
                    <span>${userName || userId}</span>
                </div>
                <div class="collab-info">Project: ${projectId}</div>
                <div class="collab-info" id="online-users">Users: 1</div>
            `
            document.body.appendChild(panel)
            
            // Set up event listeners for user join/leave events
            if (collaborationManager) {
                console.log('🎧 Setting up collaboration event listeners...')
                
                // Listen for when other users join
                collaborationManager.onUserJoined((message: any) => {
                    console.log('👋 USER_JOIN event received:', message)
                    console.log('👋 User joined:', message.userId, 'Current user:', userId)
                    updateUserCount()
                })
                
                // Listen for when other users leave
                collaborationManager.onUserLeft((message: any) => {
                    console.log('👋 USER_LEAVE event received:', message)
                    console.log('👋 User left:', message.userId, 'Current user:', userId)
                    updateUserCount()
                })
                
                // Listen for sync responses which contain active user list
                collaborationManager.onSyncResponse((message: any) => {
                    console.log('🔄 SYNC_RESPONSE event received:', message)
                    console.log('🔄 Message data:', message.data)
                    if (message.data && message.data.activeUsers) {
                        const userCount = message.data.activeUsers.length
                        console.log('👥 Active users:', message.data.activeUsers, 'Count:', userCount)
                        const usersElement = document.getElementById('online-users')
                        if (usersElement) {
                            usersElement.textContent = `Users: ${userCount}`
                            console.log('✅ Updated user count display to:', userCount)
                        } else {
                            console.warn('❌ Could not find online-users element')
                        }
                    } else {
                        console.warn('⚠️ No activeUsers in sync response data')
                    }
                })
                
                console.log('✅ Event listeners set up successfully')
            } else {
                console.error('❌ CollaborationManager is null, cannot set up event listeners')
            }
            
            // Expose diagnostic function globally for debugging
            ;(window as any).checkAudioConsistency = () => {
                if (collaborativeAgent && typeof collaborativeAgent.checkAudioFileConsistency === 'function') {
                    console.log('🔍 Running audio file consistency check...')
                    collaborativeAgent.checkAudioFileConsistency()
                } else {
                    console.error('❌ Collaborative agent not available or missing checkAudioFileConsistency method')
                }
            }
            
            // Expose fix function globally for debugging
            ;(window as any).fixDualStorage = () => {
                if (collaborativeAgent && typeof collaborativeAgent.fixDualStorage === 'function') {
                    console.log('🔧 Running dual storage fix...')
                    collaborativeAgent.fixDualStorage()
                } else {
                    console.error('❌ Collaborative agent not available or missing fixDualStorage method')
                }
            }
            
            // Function to update user count by requesting sync
            function updateUserCount() {
                console.log('🔄 updateUserCount() called')
                if (collaborationManager) {
                    console.log('📡 Requesting sync from server...')
                    collaborationManager.requestSync()
                } else {
                    console.error('❌ CollaborationManager is null in updateUserCount')
                }
            }
            
        }).catch(error => {
            console.error('❌ Failed to initialize collaboration:', error)
            console.log('🔄 Falling back to local mode')
        })
        
    } catch (error) {
        console.error('❌ Collaboration setup failed:', error)
        console.log('🔄 Using local mode')
    }
}

// Create a proxy agent that routes to the current agent
const proxyAgent = new class implements OpfsProtocol {
    async write(path: string, data: Uint8Array): Promise<void> {
        console.log(`📝 OPFS Write (${collaborationInitialized ? 'COLLABORATIVE' : 'LOCAL'}): ${path}`)
        try {
            const result = await currentOpfsAgent.write(path, data)
            console.log(`✅ OPFS Write success: ${path}`)
            return result
        } catch (error) {
            console.error(`❌ OPFS Write failed: ${path}`, error)
            console.error(`❌ OPFS Write error details:`, {
                name: error.name,
                message: error.message,
                stack: error.stack,
                path: path
            })
            throw error
        }
    }
    async read(path: string): Promise<Uint8Array> {
        console.log(`📖 OPFS Read (${collaborationInitialized ? 'COLLABORATIVE' : 'LOCAL'}): ${path}`)
        try {
            const result = await currentOpfsAgent.read(path)
            console.log(`✅ OPFS Read success: ${path} (${result.length} bytes)`)
            return result
        } catch (error) {
            console.error(`❌ OPFS Read failed: ${path}`, error)
            console.error(`❌ OPFS Read error details:`, {
                name: error.name,
                message: error.message,
                stack: error.stack,
                path: path
            })
            throw error
        }
    }
    async delete(path: string): Promise<void> {
        console.log(`🗑️ OPFS Delete (${collaborationInitialized ? 'COLLABORATIVE' : 'LOCAL'}): ${path}`)
        try {
            const result = await currentOpfsAgent.delete(path)
            console.log(`✅ OPFS Delete success: ${path}`)
            return result
        } catch (error) {
            console.error(`❌ OPFS Delete failed: ${path}`, error)
            console.error(`❌ OPFS Delete error details:`, {
                name: error.name,
                message: error.message,
                stack: error.stack,
                path: path
            })
            throw error
        }
    }
    async list(path: string): Promise<ReadonlyArray<Entry>> {
        console.log(`📋 OPFS List (${collaborationInitialized ? 'COLLABORATIVE' : 'LOCAL'}): ${path}`)
        try {
            const result = await currentOpfsAgent.list(path)
            console.log(`✅ OPFS List success: ${path} (${result.length} items)`)
            return result
        } catch (error) {
            console.error(`❌ OPFS List failed: ${path}`, error)
            console.error(`❌ OPFS List error details:`, {
                name: error.name,
                message: error.message,
                stack: error.stack,
                path: path
            })
            throw error
        }
    }
}

// Export the proxy agent
export const OpfsAgent = proxyAgent

// Get the collaborative agent for direct message handling
export function getCollaborativeAgent() {
    if (collaborationManager && (collaborationManager as any).collaborativeAgent) {
        return (collaborationManager as any).collaborativeAgent
    }
    return null
}

// Cleanup function for collaboration
export function cleanupCollaboration() {
    if (collaborationManager) {
        collaborationManager.cleanup()
        collaborationManager = null
    }
    if (collaborationInitialized && (currentOpfsAgent as any).cleanup) {
        (currentOpfsAgent as any).cleanup()
    }
    collaborationInitialized = false
    currentOpfsAgent = baseOpfsAgent
    console.log('🧹 Collaboration cleaned up')
}

// Export collaboration state for debugging
export function getCollaborationState() {
    return {
        isInitialized: collaborationInitialized,
        hasManager: !!collaborationManager,
        hasStudioService: !!studioServiceRef,
        projectId: urlParams.get('projectId'),
        userId: urlParams.get('userId')
    }
}
